---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    type: voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: voting-app
  template:
    metadata:
      name: python-pod
      labels:
        type: voting-app
    spec:
      containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_vote
...
